install.packages("duckdb")
install.packages("pROC")
install.packages("xgboost")
install.packages("kernlab")
install.packages("optparse")
install.packages("caTools")
install.packages("RANN")
install.packages("devtools")

require(devtools)
install.packages("gbm", version='2.1.8.1')